# coding: utf-8
USE_ACCOUNTS_AS_RECIPIENTS = True # SE SETAR TRUE, O PROGRAMA PEGARÁ OS PRÓPRIOS LOGINS E VAI USAR COMO RECIPIENT
PROCESSES = 4 # QUANTOS PROCESSOS SIMULTÃNEOS.
SEND_LIMIT_PER_USER = 100 # PROVEDORES SETAM LIMITES DE ENVIO DIÁRIOS POR CONTA...
HOW_MANY_LOGINS = 500 # EM QUANTOS LOGINS IRÁ TENTAR CONECTAR E MANDAR OS E-MAILS. 500 X 100 = 50.000